-- ============================================================
-- 皮肤商店 · 数据库结构
-- 在 Supabase SQL Editor 中执行
-- ============================================================

-- 1) users 表新增小七币余额字段
alter table users add column if not exists coins int not null default 0;

-- 2) 皮肤价格配置（管理员可改）
create table if not exists skin_prices (
  skin_id int primary key,
  price int not null default 100,
  duration_days int not null default 30,
  updated_at timestamptz not null default now()
);

-- 3) 购买记录
create table if not exists skin_purchases (
  id bigint generated by default as identity primary key,
  user_id bigint not null,
  skin_id int not null,
  price int not null,
  expire_at timestamptz not null,
  created_at timestamptz not null default now()
);

-- 4) 商店活动
create table if not exists shop_activities (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  discount int not null default 0,
  start_at timestamptz,
  end_at timestamptz,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

-- 5) 初始化 45 套皮肤的价格（全部 100 币 / 30 天，b0 免费可不参与）
insert into skin_prices (skin_id, price, duration_days)
select g, 100, 30 from generate_series(1, 44) as g
on conflict (skin_id) do nothing;

-- 6) 索引（查询用户购买记录 / 未过期皮肤）
create index if not exists idx_skin_purchases_user on skin_purchases(user_id);
create index if not exists idx_skin_purchases_expire on skin_purchases(expire_at);
